# Generated by Django 2.2.1 on 2019-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.CharField(max_length=100)),
                ('participant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
