# Generated by Django 2.2.1 on 2019-06-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190603_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjudicator_name', models.CharField(max_length=100)),
                ('adjudicator_institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('number_of_teams', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('participants_name', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
                ('speaker_score_range', models.CharField(max_length=100)),
                ('adjudicator_score_range', models.CharField(max_length=100)),
                ('number_of_rounds', models.CharField(max_length=100)),
                ('number_of_break_rounds', models.CharField(max_length=100)),
                ('tournament_venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
