# Generated by Django 2.2.1 on 2019-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190604_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adjudicators',
            new_name='Adjudicator',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
